version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/customer_support
      - SECRET_KEY=your-secret-key-here
      - GROQ_API_KEY=your-groq-api-key-here
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer_support
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 